insert into article (`title`, `description`) values ('Iranian (on wisdom)', 'A blind person who sees is better than a seeing person who is blind.');
insert into article (title, description) values ('English (on basic truths)', 'A crown''s no cure for a headache.');
insert into article (title, description) values ('Virgin Islander (on friendship)', 'A new broom sweeps clean but an old broom knows the corners.');
insert into article (title, description) values ('American (on proverbs)', 'A proverb is a short sentence based on long experience.');
insert into article (title, description) values ('Lord John Russell (1792-1878)', 'A proverb is one man''s wit and all men''s wisdom.');
insert into article (title, description) values ('John Heywood (c.1497-1580)', 'All''s well that ends well.');
insert into article (title, description) values ('Ralph Waldo Emerson (1803-1882)', 'Common sense is genius dressed in its working clothes.');
insert into article (title, description) values ('Chinese Proverb', 'Deal with the faults of others as gently as your own.');
insert into article (title, description) values ('French (on thrift)', 'Economy is the wealth of the poor and the wisdom of the rich.');
insert into article (title, description) values ('Korean (on common sense)', 'Even a fish wouldn''t get into trouble if it kept its mouth shut.');
insert into article (title, description) values ('unknown', 'Everything in moderation.');
insert into article (title, description) values ('Chinese Proverb', 'Give a man a fish and you feed him for a day; teach a man to fish and he''ll eat forever.');
insert into article (title, description) values ('Henry Wadsworth Longfellow (1807-1882)', 'He that respects himself is safe from others.');
insert into article (title, description) values ('Marcus Trentius Varro (c.116-27 BC)', 'He who flees at the right time can fight again.');
insert into article (title, description) values ('Friedrich Nietzsche (1844-1900)', 'He who has a why to live can bear almost any how.');
insert into article (title, description) values ('unknown', 'Health is better than wealth.');
insert into article (title, description) values ('Afghan (on time and timeliness', 'In bad things be slow; in good things be fast.');
insert into article (title, description) values ('unknown', 'Just because something is common sense doesn''t mean it''s common practice.');
insert into article (title, description) values ('Benjamin Disraeli (1804-1881)', 'Justice is truth in action.');
insert into article (title, description) values ('Cliff Nichols, acrafts@wf.net', 'Life is a journey, not a destination.');
insert into article (title, description) values ('Grandma Moses (1860-1961)', 'Life is what you make it.');
insert into article (title, description) values ('Dutch Proverb', 'Live and let live.');
insert into article (title, description) values ('Ben Franklin (1706-1790)', 'Lost time is never found again.');
insert into article (title, description) values ('Yiddish (on money)', 'Money buys everything but good sense.');
insert into article (title, description) values ('Books of the Han Dynasty', 'Nothing is impossible to the willing mind.');
insert into article (title, description) values ('Maasai(East African)(on wisdom)', 'One head cannot hold all wisdom.');
insert into article (title, description) values ('Danish (on the conduct of life)', 'One should speak little with others and much with oneself.');
insert into article (title, description) values ('unknown', 'Out of sight, out of mind.');
insert into article (title, description) values ('Japanese (on planning)', 'Plan your life at New Year''s, your day at dawn.');
insert into article (title, description) values ('unknown, courtesy of Bryan Sullivan', 'Plan your life like you will live forever, and live your life like you will die the next day.');
insert into article (title, description) values ('Sierra Leone', 'Proverbs are the daughters of experience.');
insert into article (title, description) values ('unknown', 'Silence is often misinterpreted but never misquoted.');
insert into article (title, description) values ('William Blake (1757-1827)', 'The errors of a wise man make your rule rather than the perfections of a fool.');
insert into article (title, description) values ('Alphonse Karr (1808-1890)', 'The more things change, the more they stay the same.');
insert into article (title, description) values ('Yiddish (on conscience)', 'The truly rich are those who enjoy what they have.');
insert into article (title, description) values ('French (on wisdom)', 'The wise do as much as they should, not as much as they can.');
insert into article (title, description) values ('Tibetan (on wisdom)', 'The wise understand by themselves; fools follow the reports of others.');
insert into article (title, description) values ('John Ray "What''s sauce for the goose is sauce for the gander."', 'What''s good for the goose is good for the gander.');
insert into article (title, description) values ('Chinese (on wisdom)', 'When you say one thing, the clever person understands three.');
insert into article (title, description) values ('Czech (on wisdom)', 'Wisdom is easy to carry but difficult to gather.');
insert into article (title, description) values ('William Wordsworth (1770-1850)', 'Wisdom is ofttimes nearer when we stoop than when we soar.');
insert into article (title, description) values ('unknown', 'Wisdom is to live in the present, plan for the future and profit from the past.');
insert into article (title, description) values ('Greek Proverb', 'Wonder is the beginning of wisdom,');
insert into article (title, description) values ('John Heywood (c.1497-1580)', 'You can lead a horse to water but you can''t make him drink.');
insert into article (title, description) values ('Edmund Burke (1729-1797)', 'You can never plan the future by the past.');
insert into article (title, description) values ('Portuguese Proverb', 'You can only die once.');
insert into article (title, description) values ('unknown', 'You have to take the bitter with the sweet.');
insert into article (title, description) values ('Sierra Leone', 'Proverbs are the daughters of experience.');
insert into article (title, description) values ('unknown', 'Silence is often misinterpreted but never misquoted.');
insert into article (title, description) values ('William Blake (1757-1827)', 'The errors of a wise man make your rule rather than the perfections of a fool.');
insert into article (title, description) values ('Alphonse Karr (1808-1890)', 'The more things change, the more they stay the same.');
insert into article (title, description) values ('Yiddish (on conscience)', 'The truly rich are those who enjoy what they have.');
insert into article (title, description) values ('French (on wisdom)', 'The wise do as much as they should, not as much as they can.');
insert into article (title, description) values ('Tibetan (on wisdom)', 'The wise understand by themselves; fools follow the reports of others.');
insert into article (title, description) values ('John Ray "What''s sauce for the goose is sauce for the gander."', 'What''s good for the goose is good for the gander.');
insert into article (title, description) values ('Chinese (on wisdom)', 'When you say one thing, the clever person understands three.');
insert into article (title, description) values ('Czech (on wisdom)', 'Wisdom is easy to carry but difficult to gather.');
insert into article (title, description) values ('William Wordsworth (1770-1850)', 'Wisdom is ofttimes nearer when we stoop than when we soar.');
insert into article (title, description) values ('unknown', 'Wisdom is to live in the present, plan for the future and profit from the past.');
insert into article (title, description) values ('Greek Proverb', 'Wonder is the beginning of wisdom,');
insert into article (title, description) values ('John Heywood (c.1497-1580)', 'You can lead a horse to water but you can''t make him drink.');
insert into article (title, description) values ('Edmund Burke (1729-1797)', 'You can never plan the future by the past.');
insert into article (title, description) values ('Portuguese Proverb', 'You can only die once.');
insert into article (title, description) values ('unknown', 'You have to take the bitter with the sweet.');

insert into notice (article_id) values
(4),
(11),
(23),
(49);
